# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DQWMI4HWgJ6AOfwojmWaBGN0G3aHI-H
"""

!pip install pymongo

# =========================================================
# AI Helpdesk Backend (Railway-ready, Hugging Face)
# =========================================================

# Install necessary packages (for Colab testing only)
# Remove if running on Railway, as requirements.txt handles this
# !pip install faiss-cpu -q
# !pip install pymongo -q
# !pip install sentence-transformers -q
# !pip install huggingface_hub -q

# 1️⃣ Imports
import os
import pickle
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from huggingface_hub import hf_hub_download
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from pymongo import MongoClient
from datetime import datetime, timezone

# =========================================================
# 2️⃣ Initialize FastAPI
# =========================================================
app = FastAPI()

# Enable CORS for all origins (replace "*" with your frontend URL if needed)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# =========================================================
# 3️⃣ Hugging Face paths
# =========================================================
HF_REPO = "konainzehra/helpdesk-model"  # Replace with your repo name

# If repo is private, set your token
# os.environ["HF_TOKEN"] = "<your_token_here>"

MODEL_PATH = hf_hub_download(repo_id=HF_REPO, filename="roberta-helpdesk-finetuned1/model.safetensors")
FAISS_INDEX_PATH = hf_hub_download(repo_id=HF_REPO, filename="faiss_index.bin")
DATA_PICKLE_PATH = hf_hub_download(repo_id=HF_REPO, filename="data.pkl")

# =========================================================
# 4️⃣ Load model, FAISS index, and answers
# =========================================================
embedding_model = SentenceTransformer(MODEL_PATH)
index = faiss.read_index(FAISS_INDEX_PATH)

with open(DATA_PICKLE_PATH, "rb") as f:
    answers = pickle.load(f)

# =========================================================
# 5️⃣ MongoDB setup
# =========================================================
MONGO_URL = os.environ.get("MONGO_URL")
if not MONGO_URL:
    raise ValueError("Please set the MONGO_URL environment variable with your MongoDB connection string.")

client = MongoClient(MONGO_URL)
db = client["ai_helpdesk"]
collection = db["helpdesk_logs"]

def store_log(question, answer, source="ai_helpdesk"):
    collection.insert_one({
        "question": question,
        "answer": answer,
        "source": source,
        "timestamp": datetime.now(timezone.utc)
    })

# =========================================================
# 6️⃣ Confidential filter
# =========================================================
CONFIDENTIAL_KEYWORDS = ["password", "salary", "bank", "ssn", "credit card", "confidential"]

def is_confidential(query):
    return any(word in query.lower() for word in CONFIDENTIAL_KEYWORDS)

# =========================================================
# 7️⃣ Helpdesk pipeline
# =========================================================
CONFIDENCE_THRESHOLD = 0.65

def helpdesk_pipeline(query, k=1, confidence_threshold=CONFIDENCE_THRESHOLD):
    # Confidential check
    if is_confidential(query):
        answer = "Access Restricted"
        store_log(query, answer, source="confidential_block")
        return answer

    # Encode query
    query_vec = embedding_model.encode([query], convert_to_numpy=True)
    query_vec = query_vec / np.linalg.norm(query_vec, axis=1, keepdims=True)

    # Search FAISS
    D, I = index.search(query_vec, k)
    if I[0][0] == -1:
        answer = "Please visit the official website or contact HR department at (051) 5951821."
        store_log(query, answer, source="fallback")
        return answer

    similarity = float(D[0][0])
    answer_text = answers[I[0][0]]

    # Threshold check
    if similarity < confidence_threshold:
        answer = "Please visit the official website or contact HR department at (051) 5951821."
        store_log(query, answer, source="fallback")
        return answer

    store_log(query, answer_text, source="retrieval")
    return answer_text

# =========================================================
# 8️⃣ FastAPI endpoint for frontend queries
# =========================================================
@app.post("/query")
async def query_endpoint(request: Request):
    data = await request.json()
    user_query = data.get("question")
    if not user_query:
        return {"error": "No question provided"}

    answer = helpdesk_pipeline(user_query)
    return {"answer": answer}

# =========================================================
# 9️⃣ Optional local testing
# =========================================================
if __name__ == "__main__":
    print("🤖 AI Help Desk (type 'exit' to quit)\n")
    while True:
        user_query = input("Ask your question: ")
        if user_query.lower() in ["exit", "quit"]:
            print("Goodbye 👋")
            break
        response = helpdesk_pipeline(user_query)
        print("Answer:", response)
        print("-" * 50)