# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DQWMI4HWgJ6AOfwojmWaBGN0G3aHI-H
"""

# =========================================================
# AI Helpdesk Backend (Render-ready)
# =========================================================

# 1️⃣ Imports
import os
import pickle
import numpy as np
import faiss
import pandas as pd
from datetime import datetime, timezone
from sentence_transformers import SentenceTransformer
from pymongo import MongoClient
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware

# =========================================================
# 2️⃣ Paths (all relative to main.py)
# =========================================================
MODEL_PATH = "roberta-helpdesk-finetuned1"
FAISS_INDEX_PATH = "faiss_index.bin"
DATA_PICKLE_PATH = "data.pkl"

# =========================================================
# 3️⃣ Load model, FAISS index, answers
# =========================================================
embedding_model = SentenceTransformer(MODEL_PATH)
index = faiss.read_index(FAISS_INDEX_PATH)

with open(DATA_PICKLE_PATH, "rb") as f:
    answers = pickle.load(f)

# =========================================================
# 4️⃣ MongoDB setup
# =========================================================
MONGO_URL = os.environ.get("MONGO_URL")
if not MONGO_URL:
    raise ValueError("Please set the MONGO_URL environment variable with your MongoDB connection string.")

client = MongoClient(MONGO_URL)
db = client["ai_helpdesk"]
collection = db["helpdesk_logs"]

def store_log(question, answer, source="ai_helpdesk"):
    collection.insert_one({
        "question": question,
        "answer": answer,
        "source": source,
        "timestamp": datetime.now(timezone.utc)
    })

# =========================================================
# 5️⃣ Confidential filter
# =========================================================
CONFIDENTIAL_KEYWORDS = ["password", "salary", "bank", "ssn", "credit card", "confidential"]

def is_confidential(query):
    return any(word in query.lower() for word in CONFIDENTIAL_KEYWORDS)

# =========================================================
# 6️⃣ Helpdesk pipeline
# =========================================================
CONFIDENCE_THRESHOLD = 0.65

def helpdesk_pipeline(query, k=1):
    # Check for confidential
    if is_confidential(query):
        answer = "Access Restricted"
        store_log(query, answer, "confidential_block")
        return answer

    # Encode query and normalize
    query_vec = embedding_model.encode([query], convert_to_numpy=True)
    query_vec = query_vec / np.linalg.norm(query_vec, axis=1, keepdims=True)

    # Search FAISS
    D, I = index.search(query_vec, k)
    similarity = float(D[0][0])
    answer_text = answers[I[0][0]]

    # Threshold fallback
    if similarity < CONFIDENCE_THRESHOLD:
        answer = "Please visit the official website or contact HR department."
        store_log(query, answer, "fallback")
        return answer

    # Return retrieved answer
    store_log(query, answer_text, "retrieval")
    return answer_text

# =========================================================
# 7️⃣ FastAPI App
# =========================================================
app = FastAPI()

# Enable CORS for frontend connection
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change this to your frontend domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request model
class Query(BaseModel):
    query: str

# POST endpoint
@app.post("/chat")
def chat_api(data: Query):
    answer = helpdesk_pipeline(data.query)
    return {"answer": answer}

# =========================================================
# 8️⃣ Run server (for local testing or Render)
# =========================================================
if __name__ == "__main__":
    import uvicorn
    PORT = int(os.environ.get("PORT", 10000))  # Render sets this automatically
    uvicorn.run("main:app", host="0.0.0.0", port=PORT)